#! /usr/bin/env python3
import argparse
from gitaccount import GitAccount


def main():
    parser = argparse.ArgumentParser(
             prog='gitcloner',
             description='Clone all the repositories from a github user/org\naccount to the current directory')

    accType = parser.add_mutually_exclusive_group()
    accType.add_argument('-u', '--user', help='For user accounts [DEFAULT]',
                   action='store_true')
    accType.add_argument('-o', '--org', help='For organization accounts',
                       action='store_true')

    command = parser.add_mutually_exclusive_group()
    command.add_argument('-c', '--clone',
                     help='For cloning all repos from an account.[DEFAULT]',
                     action='store_true')
    command.add_argument('-p', '--pull',
                         help='Update the existing repos of a user/org.',
                         action='store_true')

    parser.add_argument('name', help='name of the user / organization')
    args = parser.parse_args()

    if not(args.user or args.org):
        args.user = True
        print('Default account type is user account')

    if args.user:
        print('Username: {}'.format(args.name))
        accType = 'user'
    else:
        print('Organization: {}'.format(args.name))
        accType = 'org'

    account = GitAccount(accType, args.name)

    if not(args.clone or args.pull):
        args.clone = True

    if args.clone:
        account.clone_repos()
    elif args.pull:
        account.pull_repos()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('\nOperation cancelled!')
        print('Interrupted by user.')
